### ISSUE TITLE
CI agianst windows OS and macOS

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#117]
#### Task
CI against other OS:
* windows
  * this will ensure docker can be deployed to windows machines when needed
  * This will allow UAT users (with admin rights) to deploy a test environment for UAT
* MacOS 
 * will allow Mac developers / tests to have confidence they can deploy containers for testing and dev

#### Definition of Done
lets see discussion first 

#### Discussion required
Is this required? 
This will depend on how we decide to deliver a UAT environment 

**Add an _Assignee_, _Epics_, _Estimate_ and any relevant _Labels_.**

**Comment by billgeo** [comment]
> This will allow UAT users (with admin rights) to deploy a test environment for UAT

Be good to discuss this with Chris. He will need production data I suspect, so this would also require a method to copy a production snapshot. I think he has an existing UAT database, so that may be an okay way to go for now.

**Comment by billgeo** [comment]
> lets see discussion first

Would also be good to fill out the 'def of done' so we know what this actually involves. Even if the discussion means we don't end up doing it, or doing it yet.

**Comment by SPlanzer** [comment]
Not delivering
