### ISSUE TITLE
User Demo - Slides

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#152]
#### Task
Provide slides. This should be minimal as not to take much time

As per the epic this must include:
* Provide background to the DevOps approach to migrating the NZGB plugin to QGIS3.
* A demo of what has been completed to date.
* Finally, a discussion of where we are in the project and what will be delivered.

#### Definition of Done
A review has been completed by another (@billgeo ?)

#### Out of Scope
Anything to technical. Should only provide context as to why we are taking this approach

#### Discussion required
Best person to review?

**Comment by SPlanzer** [comment]
>Discussion required
>
>Best person to review?

Discussion complete, @billgeo to review

**Comment by SPlanzer** [comment]
@billgeo Please follow link for slides

https://docs.google.com/presentation/d/1kMi_L2bxSkQlMlvhvfpR3P2uE4k_hCdkILcOsQepIhs/edit#slide=id.gc6f9e470d_0_0

**Comment by billgeo** [comment]
Looks good to me @SPlanzer
