### ISSUE TITLE
 Write tests for test plan number 2 (search functionality)

### ISSUE THREAD

**Issue by strk** [linz/gazetteer#154]
Use the Gazetteer plugin to search for names and locate features

**Comment by strk** [comment]
@SPlanzer I remember some notes from you about writing tests but I can't find them now (in which ticket did you write them ?)

**Comment by SPlanzer** [comment]
not sure, I will write a quick summary here. 

LI has an adopted method for QGIS plugin tests. This follows the practices of others such as boundless (now planet).

LINZ examples include:
* https://github.com/linz/qgis-roads-plugin/tree/master/roads/tests
* https://github.com/linz/qgis-roads-plugin/tree/master/roads/tests

in the case of this plugin see:
* https://github.com/linz/gazetteer/tree/master/src/NZGBplugin/tests

Its really a case of 
* inserting an test data required into the database
* mimicking user clicks and data entries to modify data
* and then checking it has changed in the database.

I have some utility methods in [utils](https://github.com/linz/gazetteer/tree/master/src/NZGBplugin/tests/utils) for adding DB records and checking them

**Comment by SPlanzer** [comment]
closed by #172
