### ISSUE TITLE
Set up UAT Test environment

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#174]
#### Task
A test environment must be set up to allow the UAT tester to perform NZGB plugin tests

This is for the most part database related and must need to:
* Give the tester access to a NZGB database where they can perform tests without impacting production
* Be able to connect from the LINZ desktop environment 

And ideally:
* Be easy to deploy and refresh 

#### Definition of Done
Once the UAT tester can connect the plugin to the test environment 

#### Out of Scope
That depends on the option selected...

#### Discussion required
There are multiple options. What is best?
* Use the current devxxxxxx01 deployment
  * This is not easy to refresh 
* Use the docker dev environment 
  * Thus woulsd require the UAT tester to install docker and have the knowledge to use it. 
  * There is no method for loading bulk test data (only the small test integration data subset)

**Comment by billgeo** [comment]
As discussed, could also consider setting up a CD pipeline to deploy docker env to AWS (ECS?) so that NZGB staff don't need to install/use Docker themselves.

**Comment by SPlanzer** [comment]
As discussed it is a lot less effort to restore the current production db to the tstassxxxxx server for testing

**Comment by SPlanzer** [comment]
Ignore the above comment about the tst db. The UAT DB needs to be postgres8.4

**Comment by SPlanzer** [comment]
following current NZGB testing prd has been restore to devassgeo01 (db:gazetter_20200826)

**Comment by SPlanzer** [comment]
Ready to go - Closing
