### ISSUE TITLE
Document how to run a single NZGBplugin test

### ISSUE THREAD

**Issue by strk** [linz/gazetteer#176]
I understand `make docker-qgis-test` runs all modules, which is done via:
> docker-compose exec -T qgis sh -c "/usr/bin/xvfb-run -- qgis_testrunner.sh tests_directory.run_tests.run_test_modules"

But how to run a single module ? And a single test ?

**Comment by SPlanzer** [comment]
When developing tests I am using [script assistant](https://github.com/linz/qgis-scriptassistant-plugin). This allows tests to be executed inside QGIS. 

This tool was developed by Daniel Silk. The master branch only support QGIS2. I have a branch 2>3 that supports QGIS 3.
