### ISSUE TITLE
User Acceptance Testing (UAT) 

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#202]
#### Task
Confirm the QGIS3 Version of the NZGB application is operating as expected and without errors introduced by the upgrade. 

Please see issue #193 for instructions for getting the UAT version of the plugin and connecting to a test database. 

**Please ensure that it is the test database you are connected to when testing** via the plugins "About gazetteer application" tool

Please open a new GitHub issue for any new bugs found during testing. 

#### Definition of Done
Once the UAT tester has tested all major workflows

**Comment by SPlanzer** [comment]
Slack conversation captured below 
>Simon: Hi @Christopher Stephens . I have done a release (2.0.2-UAT) of the NZGB plugin where I have fixed the bugs that porting introduces and I can reproduce.
if you go to https://github.com/linz/gazetteer/issues you will see issues with the "awaiting-user-acceptance" and "release-2.0.2" labels against them. These are those that have been fixed and release.
If you fire up QGIS3 that you used for the last round of testing you should be able to go to the Plugins menu >> upgradable and select the NZGB plugin for upgrade (make sure you upgrade the 2.0.2-UAT) .
Also, ensure you are pointing at the test database by going to the Plugins menu >> Gazetteer Editor >> about gazetteer application and ensure it is pointed at DB:devassgeo01 and the database:gazetteer_20200826
Let me know if you need help with any of the above.
Once you have signed off on these bugs being fixed I will do a production release. This will require deploying the plugin to the production linz plugin repository and upgrading a database function.
Ideally this will be done by Friday the 30th Oct as this is my last day with Data Services

> Chris: I've closed all the ones labelled Awaiting User Acceptance

@CMKMS-LINZ Are you happy to go live with the state of the plugin? If so I will move on to putting together a plan to do so

**Comment by CMKMS-LINZ** [comment]
@SPlanzer No, bugs #219 , #212 basically have it unusable at the moment since we can neither add external sources of geometry (where 'multi') nor change the reference point. Bug #206 is nearly in the same category since it's so disruptive.

Bug #222 is very annoying though can be worked around.

#223, #215, #214 are probably things that could be lived with in a first release as they can be refreshed or ignored.

I have an inkling that Bug #207 may be what knocks the server offline as that is what I was retesting yesterday afternoon.

**Comment by SPlanzer** [comment]
@CMKMS-LINZ I have a new release (2.0.3-UAT) for you to upgrade to and test #219 and #212

**Comment by SPlanzer** [comment]
HI @CMKMS-LINZ 

Thanks for testing #219. Can you give #212 a test and I will then write a plan for releasing to production and migrating users to the new version.

**Comment by billgeo** [comment]
Still waiting on https://github.com/linz/gazetteer/issues/222 Can be closed once that is resolved.

**Comment by billgeo** [comment]
UAT complete and all major bugs fixed.
