### ISSUE TITLE
Geometry Layers load on default in reverse order

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#204]
### Bug Description

On starting the plugin the eight geometry layers (2 groups, four layers each) are loading in reverse order to previous behavior in 2.6.1.

This means that the points are covered by lines and polys, and line by polys.

There was also a request in the test plan to also reorder the two groups as the production default load order is unhelpful and always requires reordering manually. Users need to see the 'active' feature on top of the search result for the same feature, for visualisation, editing, etc. The active feature layers might also get buried under search results for duplications of the same name.

#### Steps to Reproduce

Turn the plugin on

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.0-UAT, QGIS 3.14.0]

#### Screenshots

Default in production plugin
![image](https://user-images.githubusercontent.com/61957082/91926790-226af400-ed2c-11ea-990c-344cef0ae025.png)

Current Default in 2.0.0-UAT:
![image](https://user-images.githubusercontent.com/61957082/91926825-39a9e180-ed2c-11ea-90c7-b9f01b968f8c.png)

Desired default order:

![image](https://user-images.githubusercontent.com/61957082/91926855-4f1f0b80-ed2c-11ea-9edc-6e7732b86d54.png)

**Comment by SPlanzer** [comment]
@CMKMS-LINZ I have released a new version of the plugin (2.0.1-UAT) to address this issue. 

Can you please install this new version and test that it resolves this issue.
