### ISSUE TITLE
Possible to create name entries with no name

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#211]
### Bug Description

If two Create new feature dialogue boxes are open, pressing OK on the 1st one will submit the details of the 2nd newer one, bypassing the check that something is entered in the Name field, eg, creating a blank entry.

This is not possible in Production plugin version 1.8.2 as the Gazetteer tools (and all other QGIS buttons, fields, etc) are locked off while the Create new feature box is open.

#### Steps to Reproduce

1. Select create new feature tool
2. Click once to open the Create new feature box
3. Click somewhere else on the map window, thereby opening a second one.
4. Enter something in the name field in the 1st box
5. Press OK
6. A new name entry is created using the details from the 2nd box, where the name field is blank

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.1 UAT, QGIS 3.14.0]

#### Screenshots

Incidentally, the name field in the blank entry has [ class=] in the name field (including the preceding space) when opened with edit.

![image](https://user-images.githubusercontent.com/61957082/92668498-1c47c980-f363-11ea-88ee-59a0637b642e.png)

**Comment by SPlanzer** [comment]
To be resolved prior to production release
