### ISSUE TITLE
Name tabs self destruct when using feature/name association links

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#213]
### Bug Description

After creating a name or feature association between two names (per step 67 onwards in test plan 1), then clicking on the new link to the other name, it will switch to the associated name, but the panel for the name you were in will self-destruct with an error message.

#### Steps to Reproduce

1): Have two names open which have a Feature/Name association created
2): On which ever name you're looking at, click on the link to the other associated name.
3): it will correctly switch over to the associated name
4): click back on the tab for the 1st name
5): See error message

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.1 UAT, QGIS 3.14.0]

#### Screenshots

![image](https://user-images.githubusercontent.com/61957082/92677120-2a074a00-f377-11ea-8a61-6c7509f79947.png)

**Comment by SPlanzer** [comment]
## Bug triage for QGIS3 initial release
Porting has introduced this bug




## Next steps
Investigate root cause and fix ready for 2.0.2 release

**Comment by SPlanzer** [comment]
when viewing the QWebFrame's url there is an evident state change before and after failure. 

from the below debug code when the name tab has not "self destructed"
```qweb_frame.url() = 'file:///home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NZGBplugin/LINZ/gazetteer/gui/html/'```

and after 

```
qweb_frame.url() = 'file:///home/splanzer/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NZGBplugin/LINZ/gazetteer/gui/html/?id=57558'
```

not after failure the url includes `?id=<name_id>`

```
from qgis.utils import plugins, iface, reloadPlugin
gazetteer_plugin = plugins.get("NZGBplugin")
controller = gazetteer_plugin._controller

views = controller.getNameViews()
qweb_dock_1 = views[1] #NameWebDock
qweb_view_1 = qweb_dock_1._nameWidget  #QWebView
qweb_page_1 = qweb_view_1.page() #QWebPage
qweb_frame = qweb_page_1.mainFrame()
print(qweb_frame.url())
```

**Comment by SPlanzer** [comment]
the ctrl click on this links works (it is left click with two NameWebView open on the same link that fails). 

is this relate to the replace method for these action 


https://github.com/linz/gazetteer/blob/661d5bc8402facfffab9634169b81bf452a3fdf8/src/NZGBplugin/LINZ/gazetteer/gui/html/js/name.js#L480-L489
