### ISSUE TITLE
Icon for 'Favouriting' name entries missing. Still useable however.

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#216]
### Bug Description

The star icon for adding a name to the favourites panel is missing and replaces with a [?] placeholder.

This can still be clicked upon to add/remove a name from the Favourites. 

This issue would probably be resolved by resolving https://github.com/linz/gazetteer/issues/210

#### Steps to Reproduce

Search/open a name. Icon is missing.

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.1, QGIS 3.14.0]

#### Screenshots

![image](https://user-images.githubusercontent.com/61957082/92680660-866e6780-f37f-11ea-99d3-fcb309b55e9d.png)

**Comment by SPlanzer** [comment]
solved by #216. 

Will be part of next UAT release
