### ISSUE TITLE
Create feature geometry Gazetteer tool no longer requires active layer to be selected, also defaults to point geometry

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#217]
### Bug Description

In production plugin 1.8.1, if no vector layer is selected, then the 'New feature geometries' tool is selected, and somewhere clicked, nothing happens. If any layer in the layer tree other than the Gazetteer feature layers is selected, an error message is thrown up (see test plan 3 step 10).

In plugin 2.0.1 UAT, if either no vector layer, or any random vector layer is selected, and then 'New feature geometries' tool is selected, and somewhere in the map window clicked, it turns on editing for the active layers, defaulting to creating a New Feature point geometry creation at the position.

This difference gives a small risk of inadvertent extra reference points being added to names.

#### Steps to Reproduce

See above

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.1 UAT QGIS 3.14]

**Comment by SPlanzer** [comment]
## Bug triage for QGIS3 initial release
A pointed out this is a deviation from expected behavior. 




### Next steps
As a first step, source code is to be reviewed as to understand how this has been introduced and it complexity. 
A solutions should be tabled

**Comment by SPlanzer** [comment]
This is a change in the QGIS3 source code. 

Porting has not modified this code and both QGIS2 and QGIS3 versions rely on actionAddFeature which returns the native QGIS Add Feature action.

In QGIS2 this tool would raise and error if the layer was not editable. 

I will add our own check to the plugin source code here

**Comment by CMKMS-LINZ** [comment]
If either the layer Gazetteer feature refpt or Gazetteer feature point is selected, in both instances it will let you create new points (the later layer being the relevant one). In both cases in only creates new points under Gazetteer feature point. 

This is acceptable - As the database only allows one reference point, presumably it would be more obvious if it were trying to create a second reference point (eg would crash)

It also does seem to hook into QGIS geometry tools, eg, you can use the Gazetteer tool to add geometry to a non gazetteer layer that is editable.
