### ISSUE TITLE
Confirmation box for editing polygons says 'lines', for lines says 'points', and for points says nothing

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#218]
### Bug Description

After selecting a geometry of any type attached to an active name entry, and using the Remove selected geometries from feature, the dialogue box says 'lines' rather than polygons when editing polygons, 'points' rather than lines when editing lines, and is missing the word editing points.

#### Steps to Reproduce

See above.

#### Desktop
 - Environment: [Windows 10]
 - Relevant Software Versions: [Gazetteer Plugin 2.0.1 UAT, QGIS 3.14.0]

#### Screenshots

**Production**

![image](https://user-images.githubusercontent.com/61957082/92683060-01d31780-f386-11ea-943d-15ab9af1a734.png)

![image](https://user-images.githubusercontent.com/61957082/92683249-858d0400-f386-11ea-93d1-37c4c97574d3.png)

**UAT**

![image](https://user-images.githubusercontent.com/61957082/92683081-10b9ca00-f386-11ea-974b-7a8f99656c3b.png)

![image](https://user-images.githubusercontent.com/61957082/92683165-4a8ad080-f386-11ea-8938-1767aec82093.png)

![image](https://user-images.githubusercontent.com/61957082/92683265-8d4ca880-f386-11ea-9b91-0568fc668aee.png)

**Comment by SPlanzer** [comment]
## Bug triage for QGIS3 initial release
Porting has introduced this bug




### Next steps
Investigate root cause and fix ready for 2.0.2 release
