### ISSUE TITLE
Gazetteer layers duplicating on search

### ISSUE THREAD

**Issue by CMKMS-LINZ** [linz/gazetteer#222]
### Bug Description
When searching and opening new entries with the Gazetteer plugin, sometimes the Search and Feature layers will duplicate in the layer tree.

#### Steps to Reproduce
Both Jill and I have had this happen but I have not been able to figure out precise steps to replicate. It may involve multiple searches in a row + changing projections.

#### Desktop
 - Environment: [e.g. Windows 10]
 - Relevant Software Versions: [e.g. Gazetteer Plugin 2.0.1 UAT, QGIS3.14.16]

#### Screenshots

![image](https://user-images.githubusercontent.com/61957082/93970782-e07d1d00-fdc2-11ea-8398-1891447c4e1f.png)

**Comment by CMKMS-LINZ** [comment]
This is definitely unhelpful

![image](https://user-images.githubusercontent.com/61957082/94104842-1e924380-fe8c-11ea-87b7-b374aa3d268b.png)

**Comment by SPlanzer** [comment]
## Bug triage for QGIS3 initial release
unable to reproduce




### Next steps
Will investigate measure to stop this occurrence

**Comment by CMKMS-LINZ** [comment]
Steps to reproduce

1. Start QGIS, turn plugin on - 
2. Conduct a search for anything, eg 'Islet'
3. Open a name, eg Islet Cove
4. Add any kind of other layer
5. Remove that layer
6. Open another name, eg Anvil Islet
7. Gazetteer layers duplicate

It seems to be the action of removing a layer from the Layers tree triggers the problem

**Comment by SPlanzer** [comment]
Thanks @CMKMS-LINZ that did it. This will make debugging many times more straight forward

**Comment by SPlanzer** [comment]
Okay, seems a QGIS3 bug is causing this and is related to `layer.loadNamedStyle`

It is similar to - http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Adding-Map-layer-to-current-project-destroy-custom-layer-variables-in-Qgis3-td5368575.html

Inshort, when setting a layer custom property via `layer.setCustomProperty` and then later loading a style for the layer via `layer.loadNamedStyle` the custom property is corrupted. 

This manifested in duplicate layers being created as when a `layerWillBeRemoved` signal is fired the plugin checks if one or more of its layers have been removed and tries to restore them. The layer.CustomProperty' layer property that was corrupted is the layer_id. This mean the plugin believed none of the layers exist and recreated them.

**Comment by SPlanzer** [comment]
To get around this, after running `layer.loadNamedStyle` I have added a second `layer.setCustomProperty` to overwrite the corrupt object with the correct layer info.

**Comment by SPlanzer** [comment]
@CMKMS-LINZ I have put a fix in place for this. Please upgrade to version 2.0.4-UAT and test
