### ISSUE TITLE
Fix admin interface tests

### ISSUE THREAD

**Issue by billgeo** [linz/gazetteer#241]
### Bug Description
These tests are mysteriously failing in CI

See tests here:
https://github.com/linz/gazetteer/blob/master/src/NZGBplugin/tests/test_admin_interface.py

#### Steps to Reproduce

See failing in CI here:
https://github.com/linz/gazetteer/actions/runs/527056317

#### Desktop
 - Github actions CI

**Comment by SPlanzer** [comment]
First test passes but failing on many  `duplicate key value violates unique constraint` errors. 


```
ERROR:  duplicate key value violates unique constraint "system_code_pkey"
DETAIL:  Key (code_group, code)=(CODE, NPRO) already exists.

ERROR:  duplicate key value violates unique constraint "system_code_pkey"
DETAIL:  Key (code_group, code)=(NSTS, UNEW) already exists.

ERROR:  duplicate key value violates unique constraint "system_code_pkey"
DETAIL:  Key (code_group, code)=(CODE, NSTS) already exists.

ERROR:  duplicate key value violates unique constraint "system_code_pkey"
DETAIL:  Key (code_group, code)=(CUSG, NPRO) already exists.

ERROR:  duplicate key value violates unique constraint "system_code_pkey"
DETAIL:  Key (code_group, code)=(CODE, NPST) already exists.

test_A_show_info (test_admin_interface.TestAdminInterface) ... ok
Error: The operation was canceled.
```

**Comment by SPlanzer** [comment]
Sorry ignore the above, I see the below and assume it was user cancelled(?). error must be in previous steps(?)

> Error: The operation was canceled.

**Comment by SPlanzer** [comment]
to be clear (for my benefit) looking at the latest [actions run](https://github.com/linz/gazetteer/actions/runs/529614920) the PG Tap tests are failing 

```
 Test Summary Report
-------------------
/sql/test/schema/schema.sql                                     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
/sql/test/schema/table_gazetteer.app_favourites.sql             (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
...
```

**Comment by billgeo** [comment]
I ended up removing the 'publish' test. It was hanging for some reason.

FYI - The PG Tap tests were failing because docker-down seems to cause issues. Removing that seems to fix it.
