### ISSUE TITLE
Run the plugin through QGIS2to3 tool

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#26]
This will involve:
* Running the QGIS plugin through the [qgis 2to3 tool](https://github.com/opengisch/qgis2to3)

The plugin is to be ported to 3.10 (as per #34)

**Comment by ccrook** [comment]
@SPlanzer Great - you are doing this ... hope it isn't too troublesome - slightly messy mixture of languages in this one!!!  Feel free to ask if you have any issues with it - not that I can remember that much about it.

**Comment by SPlanzer** [comment]
Cheers @ccrook. Will just be seeking out all API breakages so wont be diving too deep...

**Comment by SPlanzer** [comment]
Done
