### ISSUE TITLE
Proposal Sign off

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#3]
As this project is considered extra small, it is not to be signed off by LILT as outlined in the Spatial Solution Lifecycle framework but a smaller group of key stake holders.  Specifically:
- [ ] Ivan
- [x] Wendy Shaw
- [ ] Jeremy

**Comment by SPlanzer** [comment]
Below are the final points that required discussion and action prior to the proposal document sign off. 
As you see below, all points have either been actioned  or deferred to the [high level design](https://github.com/linz/gazetteer/wiki/Migration-High-Level-Design). 

@palmerj can you please review the [doc](https://linzone/id:A2848360)? and when you are comfortable with it I will send the document out for review again. 

JPs original feedback in black
```diff
+ My comments in green
- JPs further comments in red
```

Hi Simon,
 
I have reviewed the document and have the following comments:
 
1. Please clearly define the current state problem. The issues are far as I see these are:
 
i.	The operational maintenance role is not well defined or managed. E.g Jeremy and Chris do ad-hoc stuff to keep it going, not too many people know how the system was built or works.
```diff
+ I HAVE ADDED THIS CONCERN TO THE DOCUMENT. I have added a section “Production Support” it is
+ obviously important we do not over commit Data Services here – please review and comment. 
```
ii.	
ii) The server (Windows 2003) and PostgreSQL (8.4) are not well past end of life for vendor support. This cause can cause us both operational and security support issues. 
```diff 
+ ADDED TO DOC
```
iii) We do not have a robust DR or BCP plan with the business owner, meaning we are at risk if a disaster occurs.
```diff
+ The proposal outlines that we will gather RTO and RPO requirements. What else is required as part of the proposal here?

- Didn’t see that it will gather those - I must have somehow skipped over that - great then.
```


 
2. For the avoidance of doubt I would specifically state that the DR business requirements should define a RTO (Recovery Time Objective) and RPO (Recover Point Objective). 
```diff
+THE DOCUMENT HAS THE SETTING OF THESE TIME FRAMES AS A REQUIREMENT (Requirements
+ Section) I have spoken with Ivan. He is comfortable with the level of reference in the proposal 
+ document to recovery. We will establish RTO and RPO as part of the high level design requirements.
+ This will be more straight forward in the high level design phases once data volumes are understood.

- Ok as long as DR is accounted as a business requirement in brief, of course happy that it is defined in the high level design.
```

 
3. Do you think we might need some cash for the operation the new VM server and/or backup services? Unless Datacom somehow gives us a $$ credit on the decommission of the current infrastructure, then we should indicate that new on-going operating funding will be required. Maybe IS&D can help here  -  

``` diff
+ Not sure about credit but surely money will be made available as we will no longer pay for the old 
+ hardware and its support. Again is this not better suited to the high level design when we understand
+ what resources we require?
+ Does the NZGB currently contribute any costs to the database upkeep? Do I need to make them aware 
+ at this stage there will be some cost to them?

- No there is no cost transfer from the SG to DS group. I would just put 
-  it as a risk, then it can be resolved during the HLD.
```

 
4. Project Scope items. I would say the setup of backup and restore process would be another item. 
```diff
+ ADDED TO DOC
 ```

5. Out of scope - I would also add we will not be resolving the current IT security issue that allows the web database directly connect from the DMZ network to the production database within the Corporate network.
```diff
+ ADDED TO DOC
```
 
6. In the likely R&R who will be the project management? Ivan or you?
```diff
+ IVAN – Can you please comment?

- This is R&R. But again after talking to Ivan this should be defined after HLD, but before project initiation. 
```

**Comment by SPlanzer** [comment]
Hi @palmerj, I plan to place this proposal document that is currently in Objective in the wiki for this repository.

This repository is public. Can anyone see any issue with the proposal residing here?

**Comment by SPlanzer** [comment]
@palmerj, I also do understand you are busy the next few days - so when you can is fine.

cheers

**Comment by palmerj** [comment]
I don't see any issue with the proposal being public. Just make sure there is no sensitive data in it. E.g vendor commercial details.

**Comment by SPlanzer** [comment]
Hi @palmerj and @imincik can you please review the [NZ Gazetteer Database Migration Proposal document](https://linzone/id:A2848360) and provide any feedback regarding actions required to achieve document sign off.  

Changes since the last edition that have been made to reflect the updated SSF include:
* Potential costs added (I have one outstanding item here that requires feedback)
* added Desired Objectives
* added Desired Outcomes
*  Added Constraints
 * HR
 * Time
 * Financial 
 * Tolerance
 * The users(s) and other known interested parties
* Interfaces
* Project Approach  
* Acceptance Criteria

**Comment by palmerj** [comment]
@SPlanzer, I have reviewed the document. I have left a few minor comments for your consideration, but overall I endorse it. Next steps (once Ivan agrees) will be to engage Wendy and get her approval. 

Note the LINZone/objective link you provided above gives the latest published version, but you had a newer draft version that contained updated information. This got be confused for a few mins! Maybe next time just publish the document?

Thanks
Jeremy

**Comment by imincik** [comment]
Hi @SPlanzer , I wanted to review, but they are turning off Objective for night. So, I can't. It is another good reason not to store documents in progress there.

**Comment by imincik** [comment]
Objective still down. ...

**Comment by imincik** [comment]
My comments:
* In "Reasons for project": I would explain better why server needs to be decommissioned - obsolete OS, outdated DB version
In "Requirements":

**Comment by SPlanzer** [comment]
Hi @palmerj , @imincik I have made the chances requested

Ivan - You are right about Objective. I have had issues with Objective Documents freezing multiple times today. Though of more concern, as Jeremy points out above it seems the link I have shared relates to an older version. I was not aware that the link only points to published documents. 

Some reason I can not publish the document (publish is greyed-out) so I have asked that objective shared a review link with you  (this should be in your email inbox). Sorry Ivan I suspect that you will need to review this entire document as the last link was a fairly old version

**Comment by imincik** [comment]
My comments:

# Outline Business Case
## Reasons for the project
* Win 2003 and PgSQL 8.4 are unsupported (better than saying obsolete)

## Expected benefits
* I don't like last point - Cleared responsibilities

## Desired outcomes
* what is "significant maintenance" - is it PgSQL upgrade or Linux version upgrade ? If yes, Ubuntu 14.04 support ends in April 2019, not sure about PostgreSQL 9.3

# Interfaces
## Projects and programmes 
* gazetteer we application - should be "Gazetteer web application"

**Comment by SPlanzer** [comment]
```diff
- Below action taken
```

My comments:

# Outline Business Case
## Reasons for the project
* Win 2003 and PgSQL 8.4 are unsupported (better than saying obsolete)
```diff
- Done
```
## Expected benefits
* I don't like last point - Cleared responsibilities
```diff
- Removed
```
## Desired outcomes
* what is "significant maintenance" - is it PgSQL upgrade or Linux version upgrade ? If yes, Ubuntu 14.04 support ends in April 2019, not sure about PostgreSQL 9.3
```diff
- Statement removed. I should not be hard coding dates into this document as DevOps should take an agile and proactive approach to ensuring software is current. 
```
# Interfaces
## Projects and programmes 
* gazetteer we application - should be "Gazetteer web application"
```diff
- I couldn't find this - Perhaps someone fixed the typo on my behalf. 
```

**Comment by SPlanzer** [comment]
The document has just been retracted and submitted again for approval. 

The document was retracted and edit as Wendy made edits, all of which were accepted. All of these edits were grammatical in nature and did not alter the documents content.

**Comment by palmerj** [comment]
Hi @SPlanzer I have approved now.

**Comment by imincik** [comment]
Hi @SPlanzer I have also approved now. Done !
