### ISSUE TITLE
Containerisation of plugin and QGIS for testing

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#30]
The Plugin and QGIS should be containerised to allow tests to be executed against the plugin running against a instance of QGIS. This will support continuous integration validation.

Definition of Done

- [x] QGIS is running in a docker container
- [x] The plugin is installed into QGIS (running in the docker container)
- [x] The plugin code and tests can be easily executed from outside the container 
- [x] Docker container must connect with database container (docker compose)

**Comment by SPlanzer** [comment]
A good example of what this is to implement can be seen in the [nz-buildings]](https://github.com/linz/nz-buildings) project. 

As does this app, the nz-buildings plugin also has a database and qgis components dockerised.

**Comment by strk** [comment]
The docker-compose part is up and running. We now need to document and provide scripts for installing the plugin in the containerized qgis. Info on how to start qgis dockerized are here: https://github.com/qgis/QGIS/tree/master/.docker

I can start a qgis instance like this:
> docker run --rm -it --name qgis     -v /tmp/.X11-unix:/tmp/.X11-unix      -e DISPLAY=unix$DISPLAY     qgis/qgis:release-3_4 qgis

But the plugin is not installed yet, and I'm still struggling with the `qgis_setup.sh` script, part of the dockerized qgis container (from official sources) which seems to be a bit fragile

**Comment by strk** [comment]
With merging #76 we have an easy way to start qgis with plugin preinstalled

**Comment by strk** [comment]
Suonds done (and duplicated?)
