### ISSUE TITLE
Containerisation of gazetteer database

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#31]
The database must be containerised. This will support continuous integration validation as it will allow for CI to run tests against the DB.

Definition of Done:
- [ ] Gazetteer database is running in a docker container
- [ ] Docker container must connect with QGIS container (see - #95) (docker compose)

**Comment by billgeo** [comment]
Note: old version of postgres that gazetteer runs on may need to be built from source

**Comment by strk** [comment]
According to https://confluence.linz.govt.nz/display/MNAI/High+Level+Design the PostgreSQL database running in production is 8.4.

**Comment by strk** [comment]
A docker image to be used as base does exist for 8.4: https://hub.docker.com/_/postgres/?tab=tags&page=1&name=8.4

**Comment by strk** [comment]
Shall we split this repository from a separate repository containing _only_ the database schema, like it was done with linz-bde-schema ? It would basically contain what's currently under src/sql ...

**Comment by palmerj** [comment]
I think we should leave this as a mono-repo. Spliting only makes sense if another system might use it, or the components are really large. This app is pretty small and self contained

**Comment by strk** [comment]
From the README file the db schema is used both by the QGIS plugin and by the Web app ? (not sure the information there is correct).

**Comment by billgeo** [comment]
I think splitting would ultimately be a good idea (there is a slim possibility the NZGB may be extending this in the future), but I feel we can leave it for now. Unless leaving the components in the same repo is going to cause problems for us with doing the tasks we want to do now? i.e. CI/CD integration and unit testing.

**Comment by palmerj** [comment]
Ideally the web app would be in with this stuff too, but that can't occur cause a 3rd party built that. But yeah good point. Allowing the developers of the web app to reference the database component by itself potentially makes it easier for their development. But this comes at the cost of additional source code and built management.

**Comment by strk** [comment]
Simon isn't this completed ? We do have the database containerized and linked to qgis..

**Comment by SPlanzer** [comment]
Yes, Thank you
