### ISSUE TITLE
Is there a requirement for a UAT QGIS environment? 

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#33]
Will the UAT tester require a test environment that is not their day-today environment for conducting UAT testing with the plugin against QGIS3

Reasons for a test environment may include:
* Ensuring the user has access to the required QGIS version 
* Managing risk of released UAT plugin crashing QGIS3 for the user in their day-to-day environment

**Comment by SPlanzer** [comment]
I do not think this is required. 
The UAT tester will either have access to QGIS3:
* in daas and this can be configured to connect to a test database
* on a laptop which can also be configured to connect to the test database 

I suggest this issues is closed

**Comment by billgeo** [comment]
Agree. Closing. @CMKMS-LINZ also confirmed he has a UAT database he can use for testing.
