### ISSUE TITLE
Which version of QGIS should dev and UAT be against?

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#34]
Which minimum version of QGIS3 should this be ported to?
* DaaS makes available QGIS3.4
  * This took a very long time (yr+) to get installed into DaaS and thus we can expect any requests for update may also take a long time 
* Current LTR is 3.10 (released 2019-10-25)
* Next LTR is 3.16 (2020-10-23)
See [release schedule](https://www.qgis.org/en/site/getinvolved/development/roadmap.html) 
see [3.10 change log](https://qgis.org/en/site/forusers/visualchangelog310/)
https://qgis.org/en/site/forusers/visualchangelog310/

**Comment by SPlanzer** [comment]
I suggest we develop/test against QGIS 3.4 as this is what DaaS is running

This will be the plugins minimum version (will be importable to versions >) and we will assume forward compatibility with all other QGIS3 versions

**Comment by SPlanzer** [comment]
Still need agreement from Product Owner (NZGB?)

**Comment by billgeo** [comment]
Yes. We should double check with NZGB (especially about backwards compatibility). But if we have CI couldn't we test against more than one version? Like 3.4 and 3.10?

**Comment by billgeo** [comment]
Have asked Chris Stephens by email. We should probably get him on Github and interacting directly.

**Comment by billgeo** [comment]
From Chris:

> Jill, Ryan (our long term student) and I all have 3.10, being the latest release.
>
>Wendy and Daniel use 2.6.1, though do have 2.18 and 3.4 since they seem to be part of the standard DAAS Suite. But they do not use them.
>
>The Topo map picker plugin from the LINZ plugin repository which we use for BAU is compatible with 3.10 latest version, so it is highly unlikely we’ll ever use 3.4 or 2.18 again. Other plugins I favour personally (quick elevation profile, 3d rendering, and scrolling features spatially by attribute) are all compatible with the latest version.

**Comment by billgeo** [comment]
So 3.10 is the version to develop against.

**Comment by dwsilk** [comment]
Just a note / correction on a couple of dates in the first post - 3.10 did not become LTR until 21st Feb (5 days ago) and 3.16 will not be the LTR until 19th Feb 2021. So 3.10 is still pretty fresh.

Yes, using the official QGIS Docker containers, you can test against both.

In the Windows 10 thick client world, it seems administrative rights will be required by anyone with a business process need for a particular version of QGIS. Getting software packaged and updated is just too slow.

**Comment by SPlanzer** [comment]
Thanks all. I have captured the outcome of this conversation in the epic and issue to do the porting - Closed
