### ISSUE TITLE
High Level Design

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#4]
Create HL Design, review and accept it

**Comment by SPlanzer** [comment]
#2

**Comment by SPlanzer** [comment]
@imincik Can you please review and give feed back on the (gazetteer migration) [high level design](https://github.com/linz/gazetteer/wiki/Migration-High-Level-Design). 

Thanks

**Comment by imincik** [comment]
@SPlanzer , let's finish Brief first, then I will review HL design.

I am not sure if there is some problem with storing design documents in public repository. I guess not, but let's escalate this question.

@palmerj , would you please let us know if there is some legal objection or policy preventing us to keep design documents in public repository ?

**Comment by imincik** [comment]
@SPlanzer , you did lot of work on HL design. Let's finish it together. I added this as task for us two in this week.

**Comment by imincik** [comment]
I added first round of changes and cleanups to HL design

**Comment by SPlanzer** [comment]
I have acted on the TODOs in the document. 

There is mention of the DMZ and old prd server name. 
I am also gathering information to add to the document concenring current state networking. 

as some of this is a security risk I think we need to make this repo private ???

**Comment by imincik** [comment]
I changed this repository to public again and moved all Gazetteer DB migration project documents and tasks to new project repository: https://github.com/linz/gazetteer-migration

**Comment by imincik** [comment]
I renamed Gazetteer migration repo to "gazetteer-db-migration": https://github.com/linz/gazetteer-db-migration
