### ISSUE TITLE
Establish a versioning strategy

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#42]
Both QGIS2 and QGIS3 version need to be managed within the source code repo.
This will require a versioning strategy

**Comment by SPlanzer** [comment]
I suggest we create a new branch `qgis2_master` from `master` 
* `qgis2_master` - This will be for managing any bug fixing while users are still on QGIS2

All pull requests for the qgis3 migration will be into `master`

**Comment by SPlanzer** [comment]
The above has been implemented 

Note as of right now when comparing `master` and `qgis2_master` the following reported  "This branch is even with master. "

**Comment by SPlanzer** [comment]
@billgeo are you okay with this strategy? 

If so please close

**Comment by billgeo** [comment]
Yes. That's fine. I don't think we'll ever use it and we won't be backporting anything to QGIS2, but it'll be there if we need it.
