### ISSUE TITLE
Create test plan

### ISSUE THREAD

**Issue by billgeo** [linz/gazetteer#62]
### Task
We need to understand how the plugin works, the core functionality to test, and how to test it. This will be converted into automated tests. Will cover testing the plugin UI and data integrity in the database

### Definition of Done
- [ ] Test plan is complete with enough information for a developer to create automated test coverage

### Out of Scope
- LDS and other connected systems

### Discussion required
Needs discussion between devs and business SME / tester

**Comment by billgeo** [comment]
We need to understand how the plugin works, the core functionality to test, and how to test it.  This will be converted into automated tests.

Done when:

- [  ] Test plan is complete with enough information for a developer to create automated test coverage

**Comment by billgeo** [comment]
@CMKMS-LINZ as discussed, have assigned this one to you to progress. Please record all important information here and you can discuss anything with @SPlanzer over Slack or in person. Will check in next Tuesday on progress.

As discussed a spreadsheet that we can all access (not in Objective) would be fine (please post link in this issue) for this. @SPlanzer can help you shape up what information needs to go into it.

**Comment by palmerj** [comment]
I would also suggest that the UAT test plan call out what data is needed. Ideally we want to create a test plan that can use a very small (even fake) dataset that can easily be used for automatic testing.

**Comment by strk** [comment]
After looking at the state of schema creation scripts I think testing schema would also be useful.
Similar to what we do with linz-bde-schema and linz-lds-bde-schema and others, using pgtap...

**Comment by SPlanzer** [comment]
delivered by Chris

https://confluence.linz.govt.nz/display/MNAI/NZGB+Gazetter+Plugin+Tests
