### ISSUE TITLE
Update NZGB QGIS Plugin to work with 2.18

### ISSUE THREAD

**Issue by iharrison** [linz/gazetteer#8]
The NZGB plugin (https://github.com/linz/gazetteer/tree/master/src/NZGBplugin) currently is running on QGIS 2.6. It needs to be updated to 2.18 at some stage.
Can the DS Dev Team add this to their backlog of tasks?

**Comment by imincik** [comment]
@iharrison , adding to backlog.

**Comment by SPlanzer** [comment]
This might as well be ported to QGIS 3 which is going LTR in Feb 2019. 

I am closing this in favour of #13
