### ISSUE TITLE
You are using version 1.8.2 but 1.4 is latest, continue ?

### ISSUE THREAD

**Issue by strk** [linz/gazetteer#82]
The message in the subject is what comes up on first use of the gazetteer application.
It wants me to confirm I really want to keep using 1.8.2 when latest is 1.4... Wrong math ?

**Comment by SPlanzer** [comment]
related to #103? 

This is raised from 
https://github.com/linz/gazetteer/blob/9ba07fd5a11d3f5e0676cc59468e650799becaaa/src/NZGBplugin/Plugin.py#L228

Were self.Version is the version in metadata.txt and version is as stored in the db to manage database versioning

**Comment by SPlanzer** [comment]
#127 addresses this. It seems this source code does not accurately reflect what was has been deployed. 

The plugin holds the version `1.8.2` and the production DB has the DB venison also as `1.8.2`

the `1.4` in this source code does not reflect the current state of the source code deployed to the PRD DB

**Comment by strk** [comment]
Note I was talking about the _math_ used there, not necessarely the hard-coded version.
Checking for equality means you'll also get the message when you're using a NEWER version (possible to do?)
