### ISSUE TITLE
Automatically branches delete after merge 

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#84]
#### Task 
There are many branches building up in this repo. @strk pointed out other projects are setup to automatically delete branches are each merge. 

I agree this is a good idea and will look into implementing this

**Comment by SPlanzer** [comment]
done. FYI - Very straight forward via repo settings as per below

![image](https://user-images.githubusercontent.com/10425696/77709628-9e9c3580-7030-11ea-9954-3fe89d35251d.png)

**Comment by billgeo** [comment]
Nice one.
