### ISSUE TITLE
Plan for update of Gazetteer DB to support new web app

### ISSUE THREAD

**Issue by iharrison** [linz/gazetteer#9]
- [x] List required changes
- [ ] Confirm changes with Datacom and check they've been coded and in Github
- [ ] Create SQL script to apply changes to database
- [ ] Test SQL script
- [ ] Document impact on existing web app (if any)

**Comment by iharrison** [comment]
Changes required:

- Added "category" field to web gaz_code table. Modified src/sql/gazetteer_reload_web.sql and src/sql/gazetteer_web_schema.sql
- Gaz_event table added to web schema to allow the web app to filter on
event type. Modified src/sql/gazetteer_reload_web.sql and src/sql/gazetteer_web_schema.sql
- Add "FCLS" system code to web_code table. Modified src/sql/gazetteer_reload_web.sql and src/sql/gazetteer_web_schema.sql

**Comment by billgeo** [comment]
LINZ PM assigned Lorraine Want

**Comment by billgeo** [comment]
Moving to JIRA.
